In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from sklearn.preprocessing import StandardScaler
from statsmodels.graphics.tsaplots import plot_acf
import matplotlib.pyplot as plt

from catboost import CatBoostClassifier, Pool

from sklearn.metrics import accuracy_score, classification_report

In [2]:
df = pd.read_csv("/home/jupyter/project/course work/predictive-models-for-football/data/selected_leagues_one_line.csv")

In [3]:
df.head()

         date     season  ... ht_l_roll_mean_20 ht_l_roll_std_20
0  2017-08-05  2017-2018  ...               NaN              NaN
1  2017-08-12  2017-2018  ...              1.00              NaN
2  2017-08-19  2017-2018  ...              1.00              0.0
3  2017-08-26  2017-2018  ...              1.00              0.0
4  2017-09-02  2017-2018  ...              0.75              0.5

[5 rows x 427 columns]

In [4]:
df["season"]

0        2017-2018
1        2017-2018
2        2017-2018
3        2017-2018
4        2017-2018
           ...
41835    2018-2019
41836    2018-2019
41837    2018-2019
41838    2018-2019
41839    2018-2019
Name: season, Length: 41840, dtype: object

In [5]:
df = df.sort_values(by=["date"])
df

             date     season  ... ht_l_roll_mean_20 ht_l_roll_std_20
3823   2017-07-28  2017-2018  ...          0.315789         0.477567
35090  2017-07-28  2017-2018  ...          0.157895         0.374634
11417  2017-07-29  2017-2018  ...          0.263158         0.452414
2526   2017-07-29  2017-2018  ...          0.052632         0.229416
38352  2017-07-29  2017-2018  ...          0.210526         0.418854
...           ...        ...  ...               ...              ...
4770   2025-05-25  2024-2025  ...          0.450000         0.510418
38007  2025-05-25  2024-2025  ...          0.500000         0.512989
20044  2025-05-25  2024-2025  ...          0.500000         0.512989
26084  2025-05-25  2024-2025  ...          0.200000         0.410391
1017   2025-05-25  2024-2025  ...          0.150000         0.366348

[41840 rows x 427 columns]

In [14]:
cat_columns = [
    "referee",
    "team",
    "enemy_team",
    "league_code"
]

In [15]:
unknown_cols = [
    "match_result", 
    "ftg", 
    "enemy_ftg", 
    "s",
    "st",
    "f",
    "c",
    "y",
    "r",
    "enemy_s",
    "enemy_st",
    "enemy_f",
    "enemy_c",
    "enemy_y",
    "enemy_r",
    "ht_w",
    "ht_d",
    "ht_l",
    "date",
    "season"
    ]

In [16]:
numeric_columns = list(set(df.columns) - set(cat_columns) - set(unknown_cols))
len(numeric_columns)

403

Одна модель на все команды (ряды)

In [17]:
val_season = "2024-2025"

In [18]:
df.head()

             date     season  ... ht_l_roll_mean_20 ht_l_roll_std_20
3823   2017-07-28  2017-2018  ...          0.315789         0.477567
35090  2017-07-28  2017-2018  ...          0.157895         0.374634
11417  2017-07-29  2017-2018  ...          0.263158         0.452414
2526   2017-07-29  2017-2018  ...          0.052632         0.229416
38352  2017-07-29  2017-2018  ...          0.210526         0.418854

[5 rows x 427 columns]

In [19]:
kfold_steps = 5

In [20]:
acc_scores = []
for i in range(kfold_steps):
    kfold_step = i + 1

    val_df = df[df["season"] == val_season]
    fold_size = val_df.shape[0] // (kfold_steps + 2)
    val_size = min(200, fold_size)
    train_date_thr = ""
    val_date_thr = ""
    for date in sorted(val_df["date"].unique()):
        if train_date_thr != "" and val_df[val_df["date"] <= date].shape[0] > fold_size * kfold_step:
            break
        train_date_thr = date

    for date in sorted(val_df["date"].unique()):
        if val_date_thr != "" and val_df[(val_df["date"] <= date) & (val_df["date"] > train_date_thr)].shape[0] > val_size:
            break
        val_date_thr = date

    assert train_date_thr < val_date_thr

    X_train = df[~(
        (df["season"] == val_season)
        & (df["date"] > train_date_thr)
    )]
    
    X_val = df[(
        (df["season"] == val_season)
        & (df["date"] < val_date_thr) & (df["date"] > train_date_thr)
    )]
        
    X_test = df[(
        (df["season"] == val_season)
        & (df["date"] >= val_date_thr)
    )]
    
    y_train = X_train["match_result"]
    X_train = X_train.drop(columns=unknown_cols)

    y_val = X_val["match_result"]
    X_val = X_val.drop(columns=unknown_cols)
    
    y_test = X_test["match_result"]
    X_test = X_test.drop(columns=unknown_cols)
    
    print(X_train.shape, X_val.shape, X_test.shape)

    train_pool = Pool(
        data=X_train,
        label=y_train,
        cat_features=cat_columns
    )
    
    val_pool = Pool(
        data=X_val,
        label=y_val,
        cat_features=cat_columns
    )

    test_pool = Pool(
        data=X_test,
        label=y_test,
        cat_features=cat_columns
    )

    model = CatBoostClassifier(
        iterations=3000,
        learning_rate=0.005,
        depth=6,
        loss_function='MultiClass',
        random_seed=42,
        verbose=100,
        cat_features=cat_columns,
    )
    model.fit(
        X_train, y_train,
        eval_set=(X_val, y_val),
        early_stopping_rounds=50,
        verbose=100
    )

    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)
    
    acc_score = accuracy_score(y_test, y_pred)
    acc_scores.append(acc_score)
    
    print("="*50)
    print(i, acc_score)
    print("="*50)
          
print(np.mean(acc_scores))

(37298, 407) (186, 407) (4356, 407)
0:	learn: 1.0983567	test: 1.0984215	best: 1.0984215 (0)	total: 113ms	remaining: 5m 38s
100:	learn: 1.0725733	test: 1.0801624	best: 1.0801624 (100)	total: 4.07s	remaining: 1m 56s
200:	learn: 1.0606014	test: 1.0729964	best: 1.0729964 (200)	total: 8.14s	remaining: 1m 53s
300:	learn: 1.0540332	test: 1.0701340	best: 1.0701340 (300)	total: 12.2s	remaining: 1m 49s
400:	learn: 1.0498269	test: 1.0686497	best: 1.0686387 (399)	total: 16.3s	remaining: 1m 45s
500:	learn: 1.0467268	test: 1.0678138	best: 1.0676403 (482)	total: 20.4s	remaining: 1m 41s
600:	learn: 1.0441257	test: 1.0670241	best: 1.0670193 (599)	total: 24.5s	remaining: 1m 37s
700:	learn: 1.0419205	test: 1.0665926	best: 1.0665601 (654)	total: 28.6s	remaining: 1m 33s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.06656013
bestIteration = 654

Shrink model to first 655 iterations.
==================================================
0 0.453168044077135
==================================================
(38052, 407) (188, 407) (3600, 407)
0:	learn: 1.0982940	test: 1.0986087	best: 1.0986087 (0)	total: 47.7ms	remaining: 2m 23s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.097647781
bestIteration = 33

Shrink model to first 34 iterations.
==================================================
1 0.4558333333333333
==================================================
(38812, 407) (130, 407) (2898, 407)
0:	learn: 1.0983405	test: 1.0982744	best: 1.0982744 (0)	total: 52.1ms	remaining: 2m 36s
100:	learn: 1.0726463	test: 1.0750890	best: 1.0750890 (100)	total: 3.96s	remaining: 1m 53s
200:	learn: 1.0607936	test: 1.0645004	best: 1.0645004 (200)	total: 8.01s	remaining: 1m 51s
300:	learn: 1.0543160	test: 1.0607048	best: 1.0606630 (299)	total: 12.1s	remaining: 1m 48s
400:	learn: 1.0502953	test: 1.0580615	best: 1.0580091 (398)	total: 16.4s	remaining: 1m 46s
500:	learn: 1.0473005	test: 1.0561143	best: 1.0561143 (500)	total: 20.7s	remaining: 1m 43s
600:	learn: 1.0446077	test: 1.0552833	best: 1.0552112 (597)	total: 24.9s	remaining: 1m 39s
700:	learn: 1.0425169	test: 1.0549880	best: 1.0548532 (653)	total: 29.2s	remaining: 1m 35s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.054853154
bestIteration = 653

Shrink model to first 654 iterations.
==================================================
2 0.45410628019323673
==================================================
(39522, 407) (164, 407) (2154, 407)
0:	learn: 1.0982328	test: 1.0980796	best: 1.0980796 (0)	total: 51.4ms	remaining: 2m 34s
100:	learn: 1.0730872	test: 1.0660472	best: 1.0660472 (100)	total: 4.08s	remaining: 1m 57s
200:	learn: 1.0609237	test: 1.0501219	best: 1.0501219 (200)	total: 8.25s	remaining: 1m 54s
300:	learn: 1.0544426	test: 1.0415453	best: 1.0415453 (300)	total: 12.5s	remaining: 1m 52s
400:	learn: 1.0503322	test: 1.0370032	best: 1.0370032 (400)	total: 16.8s	remaining: 1m 48s
500:	learn: 1.0472489	test: 1.0343882	best: 1.0343882 (500)	total: 21.1s	remaining: 1m 45s
600:	learn: 1.0447221	test: 1.0328001	best: 1.0328001 (600)	total: 25.4s	remaining: 1m 41s
700:	learn: 1.0426388	test: 1.0319725	best: 1.0319230 (698)	total: 29.7s	remaining: 1m 37s
800:	learn: 1.0407474	test: 1.0314855	best: 1.0314855 (800)	total: 34s	remaining: 1m 33s
900:	learn: 1.0390968	test: 1.0310429	best: 1.0310429 (900)	total: 38.3s	remaining: 1m 29s
1000:	learn: 1.0375224	test: 1.0305537	best: 1.0305028 (996)	total: 42.7s	remaining: 1m 25s
1100:	learn: 1.0360820	test: 1.0300644	best: 1.0300424 (1098)	total: 47.1s	remaining: 1m 21s
1200:	learn: 1.0347501	test: 1.0299464	best: 1.0298631 (1187)	total: 51.4s	remaining: 1m 17s
1300:	learn: 1.0333952	test: 1.0298755	best: 1.0297844 (1282)	total: 55.8s	remaining: 1m 12s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.029784419
bestIteration = 1282

Shrink model to first 1283 iterations.
==================================================
3 0.44614670380687094
==================================================
(40290, 407) (146, 407) (1404, 407)
0:	learn: 1.0982448	test: 1.0983066	best: 1.0983066 (0)	total: 48.4ms	remaining: 2m 25s
100:	learn: 1.0724339	test: 1.0823528	best: 1.0823528 (100)	total: 4.04s	remaining: 1m 55s
200:	learn: 1.0606073	test: 1.0760989	best: 1.0760989 (200)	total: 8.14s	remaining: 1m 53s
300:	learn: 1.0542991	test: 1.0727388	best: 1.0727388 (300)	total: 12.3s	remaining: 1m 50s
400:	learn: 1.0502147	test: 1.0716273	best: 1.0716273 (400)	total: 16.4s	remaining: 1m 46s
500:	learn: 1.0471529	test: 1.0704170	best: 1.0704170 (500)	total: 20.5s	remaining: 1m 42s
600:	learn: 1.0445630	test: 1.0693935	best: 1.0693081 (588)	total: 24.4s	remaining: 1m 37s
700:	learn: 1.0424386	test: 1.0684635	best: 1.0684545 (699)	total: 28.4s	remaining: 1m 33s
800:	learn: 1.0405036	test: 1.0678745	best: 1.0678333 (799)	total: 32.4s	remaining: 1m 28s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.067772787
bestIteration = 815

Shrink model to first 816 iterations.
==================================================
4 0.44017094017094016
==================================================
0.44988506031630326

то же самое но обучаемся на последний сезон

In [70]:
acc_scores = []
for i in range(n - 10 - 1, n-1):
    X_train = df_with_tour[(df_with_tour["season"] == val_season) & (df_with_tour["tour"] < i)].drop(columns=unknown_cols)
    y_train = df_with_tour[(df_with_tour["season"] == val_season) & (df_with_tour["tour"] < i)]["match_result"]

    X_val = df_with_tour[(df_with_tour["season"] == val_season) & (df_with_tour["tour"] == i)].drop(columns=unknown_cols)
    y_val = df_with_tour[(df_with_tour["season"] == val_season) & (df_with_tour["tour"] == i)]["match_result"]
    
    X_test = df_with_tour[(df_with_tour["season"] == val_season) & (df_with_tour["tour"] == i + 1)].drop(columns=unknown_cols)
    y_test = df_with_tour[(df_with_tour["season"] == val_season) & (df_with_tour["tour"] == i + 1)]["match_result"]

    train_pool = Pool(
        data=X_train,
        label=y_train,
        cat_features=cat_columns
    )
    
    val_pool = Pool(
        data=X_val,
        label=y_val,
        cat_features=cat_columns
    )

    test_pool = Pool(
        data=X_test,
        label=y_test,
        cat_features=cat_columns
    )

    model = CatBoostClassifier(
        iterations=3000,
        learning_rate=0.005,
        depth=6,
        loss_function='MultiClass',
        random_seed=42,
        verbose=100,
        cat_features=cat_columns,
    )
    model.fit(
        X_train, y_train,
        eval_set=(X_val, y_val),
        early_stopping_rounds=50,
        verbose=100
    )

    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)
    
    acc_score = accuracy_score(y_test, y_pred)
    acc_scores.append(acc_score)
    
    print("="*50)
    print(i, acc_score)
    print("="*50)
          
print(np.mean(acc_scores))

0:	learn: 1.0979129	test: 1.0978705	best: 1.0978705 (0)	total: 47.7ms	remaining: 2m 23s
100:	learn: 1.0293662	test: 1.0576783	best: 1.0576783 (100)	total: 4.31s	remaining: 2m 3s
200:	learn: 0.9761475	test: 1.0337912	best: 1.0337912 (200)	total: 8.55s	remaining: 1m 59s
300:	learn: 0.9315161	test: 1.0143083	best: 1.0143083 (300)	total: 12.9s	remaining: 1m 55s
400:	learn: 0.8927027	test: 1.0045730	best: 1.0045730 (400)	total: 17s	remaining: 1m 50s
500:	learn: 0.8586713	test: 0.9999159	best: 0.9999159 (500)	total: 21.1s	remaining: 1m 45s
600:	learn: 0.8271825	test: 0.9924402	best: 0.9924402 (600)	total: 25.5s	remaining: 1m 41s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.9899244988
bestIteration = 641

Shrink model to first 642 iterations.
==================================================
31 0.6
==================================================
0:	learn: 1.0979687	test: 1.0981356	best: 1.0981356 (0)	total: 49.8ms	remaining: 2m 29s
100:	learn: 1.0306649	test: 1.0685476	best: 1.0685476 (100)	total: 4.15s	remaining: 1m 59s
200:	learn: 0.9790650	test: 1.0506415	best: 1.0506415 (200)	total: 8.33s	remaining: 1m 56s
300:	learn: 0.9346115	test: 1.0354589	best: 1.0354589 (300)	total: 12.5s	remaining: 1m 52s
400:	learn: 0.8962858	test: 1.0265971	best: 1.0265971 (400)	total: 16.7s	remaining: 1m 48s
500:	learn: 0.8634384	test: 1.0229939	best: 1.0228903 (497)	total: 21.1s	remaining: 1m 45s
600:	learn: 0.8341075	test: 1.0205248	best: 1.0204575 (571)	total: 25.2s	remaining: 1m 40s
700:	learn: 0.8050013	test: 1.0173476	best: 1.0169257 (696)	total: 29.7s	remaining: 1m 37s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.016764507
bestIteration = 720

Shrink model to first 721 iterations.
==================================================
32 0.45
==================================================
0:	learn: 1.0977126	test: 1.0983491	best: 1.0983491 (0)	total: 34.4ms	remaining: 1m 43s
100:	learn: 1.0303950	test: 1.0835586	best: 1.0834281 (92)	total: 4.14s	remaining: 1m 58s
200:	learn: 0.9773736	test: 1.0703456	best: 1.0703456 (200)	total: 8.27s	remaining: 1m 55s
300:	learn: 0.9337570	test: 1.0681383	best: 1.0679794 (288)	total: 12.6s	remaining: 1m 53s
400:	learn: 0.8976416	test: 1.0671074	best: 1.0659229 (388)	total: 16.7s	remaining: 1m 48s
500:	learn: 0.8647786	test: 1.0612505	best: 1.0612505 (500)	total: 20.8s	remaining: 1m 43s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.061244646
bestIteration = 503

Shrink model to first 504 iterations.
==================================================
33 0.45
==================================================
0:	learn: 1.0977998	test: 1.0981956	best: 1.0981956 (0)	total: 34.6ms	remaining: 1m 43s
100:	learn: 1.0319301	test: 1.0730813	best: 1.0729698 (99)	total: 4.3s	remaining: 2m 3s
200:	learn: 0.9812337	test: 1.0629835	best: 1.0629835 (200)	total: 8.37s	remaining: 1m 56s
300:	learn: 0.9397938	test: 1.0565730	best: 1.0565730 (300)	total: 12.6s	remaining: 1m 53s
400:	learn: 0.9021302	test: 1.0487705	best: 1.0486060 (388)	total: 16.9s	remaining: 1m 49s
500:	learn: 0.8682478	test: 1.0477005	best: 1.0465642 (468)	total: 21.2s	remaining: 1m 45s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.046298467
bestIteration = 528

Shrink model to first 529 iterations.
==================================================
34 0.5
==================================================
0:	learn: 1.0979395	test: 1.0986686	best: 1.0986686 (0)	total: 35.5ms	remaining: 1m 46s
100:	learn: 1.0337072	test: 1.0861251	best: 1.0861251 (100)	total: 4.21s	remaining: 2m
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.081638599
bestIteration = 131

Shrink model to first 132 iterations.
==================================================
35 0.5625
==================================================
0:	learn: 1.0978506	test: 1.0970621	best: 1.0970621 (0)	total: 48.6ms	remaining: 2m 25s
100:	learn: 1.0332530	test: 1.0416173	best: 1.0416173 (100)	total: 4.31s	remaining: 2m 3s
200:	learn: 0.9822279	test: 0.9998634	best: 0.9998634 (200)	total: 8.38s	remaining: 1m 56s
300:	learn: 0.9409249	test: 0.9687328	best: 0.9687328 (300)	total: 12.6s	remaining: 1m 53s
400:	learn: 0.9056349	test: 0.9471344	best: 0.9471344 (400)	total: 16.9s	remaining: 1m 49s
500:	learn: 0.8737908	test: 0.9323304	best: 0.9323304 (500)	total: 21.1s	remaining: 1m 45s
600:	learn: 0.8439577	test: 0.9245386	best: 0.9245386 (600)	total: 25.4s	remaining: 1m 41s
700:	learn: 0.8166248	test: 0.9142150	best: 0.9142150 (700)	total: 29.5s	remaining: 1m 36s
800:	learn: 0.7903854	test: 0.9115044	best: 0.9115044 (800)	total: 33.7s	remaining: 1m 32s
900:	learn: 0.7658859	test: 0.9078170	best: 0.9069468 (889)	total: 37.9s	remaining: 1m 28s
1000:	learn: 0.7422912	test: 0.9026235	best: 0.9021085 (993)	total: 42.1s	remaining: 1m 24s
1100:	learn: 0.7199969	test: 0.8997907	best: 0.8981223 (1079)	total: 46.3s	remaining: 1m 19s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.8981222846
bestIteration = 1079

Shrink model to first 1080 iterations.
==================================================
36 0.6666666666666666
==================================================
0:	learn: 1.0979834	test: 1.0976895	best: 1.0976895 (0)	total: 49ms	remaining: 2m 26s
100:	learn: 1.0327211	test: 1.0122758	best: 1.0122758 (100)	total: 4.12s	remaining: 1m 58s
200:	learn: 0.9828255	test: 0.9630174	best: 0.9630174 (200)	total: 8.34s	remaining: 1m 56s
300:	learn: 0.9432306	test: 0.9280081	best: 0.9280081 (300)	total: 12.6s	remaining: 1m 53s
400:	learn: 0.9068349	test: 0.9019607	best: 0.9019607 (400)	total: 16.6s	remaining: 1m 47s
500:	learn: 0.8760319	test: 0.8830525	best: 0.8830525 (500)	total: 20.8s	remaining: 1m 43s
600:	learn: 0.8460443	test: 0.8674846	best: 0.8674846 (600)	total: 24.8s	remaining: 1m 38s
700:	learn: 0.8191291	test: 0.8532172	best: 0.8532172 (700)	total: 28.9s	remaining: 1m 34s
800:	learn: 0.7925298	test: 0.8376897	best: 0.8376897 (800)	total: 33.2s	remaining: 1m 31s
900:	learn: 0.7683594	test: 0.8298809	best: 0.8297444 (899)	total: 37.3s	remaining: 1m 26s
1000:	learn: 0.7458449	test: 0.8191485	best: 0.8191485 (1000)	total: 41.4s	remaining: 1m 22s
1100:	learn: 0.7226085	test: 0.8134612	best: 0.8134612 (1100)	total: 45.5s	remaining: 1m 18s
1200:	learn: 0.7013360	test: 0.8056131	best: 0.8056131 (1200)	total: 49.5s	remaining: 1m 14s
1300:	learn: 0.6780862	test: 0.8002994	best: 0.8002994 (1300)	total: 53.8s	remaining: 1m 10s
1400:	learn: 0.6553006	test: 0.7935375	best: 0.7933956 (1394)	total: 58s	remaining: 1m 6s
1500:	learn: 0.6334264	test: 0.7880464	best: 0.7880417 (1499)	total: 1m 2s	remaining: 1m 2s
1600:	learn: 0.6110280	test: 0.7812075	best: 0.7811574 (1599)	total: 1m 6s	remaining: 58s
1700:	learn: 0.5901602	test: 0.7771719	best: 0.7771197 (1698)	total: 1m 10s	remaining: 54s
1800:	learn: 0.5684656	test: 0.7751334	best: 0.7748530 (1769)	total: 1m 14s	remaining: 49.9s
1900:	learn: 0.5481720	test: 0.7724903	best: 0.7718196 (1875)	total: 1m 19s	remaining: 45.8s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.7718195531
bestIteration = 1875

Shrink model to first 1876 iterations.
==================================================
37 0.2
==================================================
0:	learn: 1.0979594	test: 1.0985974	best: 1.0985974 (0)	total: 35.1ms	remaining: 1m 45s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.098597372
bestIteration = 0

Shrink model to first 1 iterations.
==================================================
38 0.5
==================================================
0:	learn: 1.0979125	test: 1.0985695	best: 1.0985695 (0)	total: 48.9ms	remaining: 2m 26s
100:	learn: 1.0312230	test: 1.0984838	best: 1.0937723 (55)	total: 4.15s	remaining: 1m 59s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.093772271
bestIteration = 55

Shrink model to first 56 iterations.
==================================================
39 0.7
==================================================
0:	learn: 1.0980521	test: 1.0980020	best: 1.0980020 (0)	total: 45.1ms	remaining: 2m 15s
100:	learn: 1.0357422	test: 1.0366468	best: 1.0366468 (100)	total: 4.3s	remaining: 2m 3s
200:	learn: 0.9871463	test: 0.9907385	best: 0.9907385 (200)	total: 8.62s	remaining: 1m 59s
300:	learn: 0.9470620	test: 0.9563537	best: 0.9563537 (300)	total: 13s	remaining: 1m 56s
400:	learn: 0.9119784	test: 0.9385040	best: 0.9384498 (398)	total: 17.1s	remaining: 1m 50s
500:	learn: 0.8808499	test: 0.9240351	best: 0.9235886 (496)	total: 21.3s	remaining: 1m 46s
600:	learn: 0.8520584	test: 0.9109507	best: 0.9109507 (600)	total: 25.5s	remaining: 1m 41s
700:	learn: 0.8259929	test: 0.9006032	best: 0.9004356 (696)	total: 29.6s	remaining: 1m 36s
800:	learn: 0.8023349	test: 0.8939176	best: 0.8935643 (797)	total: 33.8s	remaining: 1m 32s
900:	learn: 0.7783044	test: 0.8889910	best: 0.8888869 (891)	total: 38.1s	remaining: 1m 28s
1000:	learn: 0.7562488	test: 0.8861159	best: 0.8844214 (986)	total: 42.2s	remaining: 1m 24s
1100:	learn: 0.7348836	test: 0.8827727	best: 0.8825105 (1098)	total: 46.4s	remaining: 1m 20s
1200:	learn: 0.7137332	test: 0.8793093	best: 0.8792520 (1199)	total: 50.6s	remaining: 1m 15s
1300:	learn: 0.6929485	test: 0.8771280	best: 0.8769257 (1298)	total: 55s	remaining: 1m 11s
1400:	learn: 0.6723203	test: 0.8751689	best: 0.8751579 (1391)	total: 59.5s	remaining: 1m 7s
1500:	learn: 0.6506529	test: 0.8690639	best: 0.8690639 (1500)	total: 1m 3s	remaining: 1m 3s
1600:	learn: 0.6296022	test: 0.8665902	best: 0.8665902 (1600)	total: 1m 8s	remaining: 59.6s
1700:	learn: 0.6087644	test: 0.8628718	best: 0.8628718 (1700)	total: 1m 12s	remaining: 55.4s
1800:	learn: 0.5888449	test: 0.8595266	best: 0.8595266 (1800)	total: 1m 16s	remaining: 51.2s
1900:	learn: 0.5686807	test: 0.8565691	best: 0.8565691 (1900)	total: 1m 21s	remaining: 46.9s
2000:	learn: 0.5491906	test: 0.8520149	best: 0.8515714 (1991)	total: 1m 25s	remaining: 42.6s
2100:	learn: 0.5304475	test: 0.8503308	best: 0.8502233 (2064)	total: 1m 29s	remaining: 38.3s
2200:	learn: 0.5134881	test: 0.8493307	best: 0.8487759 (2193)	total: 1m 33s	remaining: 34s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.8487758522
bestIteration = 2193

Shrink model to first 2194 iterations.
==================================================
40 0.6
==================================================
0.5229166666666666