In [59]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from sklearn.preprocessing import StandardScaler
from statsmodels.graphics.tsaplots import plot_acf
import matplotlib.pyplot as plt

from catboost import CatBoostClassifier, Pool

from sklearn.metrics import accuracy_score, classification_report

In [7]:
df = pd.read_csv("/home/jupyter/project/course work/1/try to predict one line/epl_one_line.csv")

In [8]:
df.head()

         date     season  ... ht_l_roll_mean_20 ht_l_roll_std_20
0  2000-08-19  2000-2001  ...               NaN              NaN
1  2000-08-21  2000-2001  ...          0.000000              NaN
2  2000-08-26  2000-2001  ...          0.000000          0.00000
3  2000-09-06  2000-2001  ...          0.333333          0.57735
4  2000-09-09  2000-2001  ...          0.500000          0.57735

[5 rows x 426 columns]

In [9]:
df["season"]

0        2000-2001
1        2000-2001
2        2000-2001
3        2000-2001
4        2000-2001
           ...
18815    2024-2025
18816    2024-2025
18817    2024-2025
18818    2024-2025
18819    2024-2025
Name: season, Length: 18820, dtype: object

In [10]:
df = df.sort_values(by=["date"])
df

             date     season  ... ht_l_roll_mean_20 ht_l_roll_std_20
0      2000-08-19  2000-2001  ...               NaN              NaN
4098   2000-08-19  2000-2001  ...          0.421053         0.507257
8194   2000-08-19  2000-2001  ...          0.263158         0.452414
4356   2000-08-19  2000-2001  ...          0.368421         0.495595
17267  2000-08-19  2000-2001  ...          0.368421         0.495595
...           ...        ...  ...               ...              ...
3185   2025-05-25  2024-2025  ...          0.450000         0.510418
18102  2025-05-25  2024-2025  ...          0.450000         0.510418
1767   2025-05-25  2024-2025  ...          0.250000         0.444262
7932   2025-05-25  2024-2025  ...          0.500000         0.512989
18819  2025-05-25  2024-2025  ...          0.400000         0.502625

[18820 rows x 426 columns]

In [19]:
val_season = "2024-2025"

In [11]:
df_with_tour = []
prev_season = ""
tour_teams = set()
tour = 1
for index, row in df.copy().iterrows():
    curr_row = row.copy()
    if curr_row["season"] != prev_season:
        prev_season = row["season"]
        tour = 1
        tour_teams = set()
    if curr_row["team"] in tour_teams:
        tour += 1
        tour_teams = set()
    tour_teams.add(curr_row["team"])
    curr_row["tour"] = tour
    df_with_tour.append(curr_row)

In [13]:
df_with_tour = pd.DataFrame(df_with_tour)

In [15]:
df_with_tour

             date     season  ... ht_l_roll_std_20 tour
0      2000-08-19  2000-2001  ...              NaN    1
4098   2000-08-19  2000-2001  ...         0.507257    1
8194   2000-08-19  2000-2001  ...         0.452414    1
4356   2000-08-19  2000-2001  ...         0.495595    1
17267  2000-08-19  2000-2001  ...         0.495595    1
...           ...        ...  ...              ...  ...
3185   2025-05-25  2024-2025  ...         0.510418   41
18102  2025-05-25  2024-2025  ...         0.510418   41
1767   2025-05-25  2024-2025  ...         0.444262   41
7932   2025-05-25  2024-2025  ...         0.512989   41
18819  2025-05-25  2024-2025  ...         0.502625   41

[18820 rows x 427 columns]

In [26]:
df_with_tour.columns[:50]

Index(['date', 'season', 'referee', 'team', 'enemy_team', 'match_result',
       'ftg', 'enemy_ftg', 's', 'st', 'f', 'c', 'y', 'r', 'enemy_s',
       'enemy_st', 'enemy_f', 'enemy_c', 'enemy_y', 'enemy_r', 'ht_w', 'ht_d',
       'ht_l', 'match_result_diff1', 'year', 'month', 'day', 'dow',
       'weekofyear', 'is_weekend', 'match_result_lag_1', 'match_result_lag_2',
       'match_result_lag_3', 'match_result_lag_4', 'match_result_lag_5',
       'ftg_lag_1', 'ftg_lag_2', 'ftg_lag_3', 'ftg_lag_4', 'ftg_lag_5',
       'enemy_ftg_lag_1', 'enemy_ftg_lag_2', 'enemy_ftg_lag_3',
       'enemy_ftg_lag_4', 'enemy_ftg_lag_5', 's_lag_1', 's_lag_2', 's_lag_3',
       's_lag_4', 's_lag_5'],
      dtype='object')

In [52]:
cat_columns = [
    "referee",
    "team",
    "enemy_team"
]

In [53]:
unknown_cols = [
    "match_result", 
    "ftg", 
    "enemy_ftg", 
    "s",
    "st",
    "f",
    "c",
    "y",
    "r",
    "enemy_s",
    "enemy_st",
    "enemy_f",
    "enemy_c",
    "enemy_y",
    "enemy_r",
    "ht_w",
    "ht_d",
    "ht_l",
    "date",
    "season"
    ]

In [54]:
numeric_columns = list(set(df_with_tour.columns) - set(cat_columns) - set(unknown_cols))
len(numeric_columns)

404

In [55]:
df_with_tour[df_with_tour["season"] == val_season]["tour"]

11468     1
7515      1
13080     1
1730      1
6841      1
         ..
3185     41
18102    41
1767     41
7932     41
18819    41
Name: tour, Length: 760, dtype: int64

In [56]:
n = 42

Одна модель на все команды (ряды)

In [69]:
acc_scores = []
for i in range(n - 10 - 1, n-1):
    X_train = df_with_tour[~((df_with_tour["season"] == val_season) & (df_with_tour["tour"] >= i))].drop(columns=unknown_cols)
    y_train = df_with_tour[~((df_with_tour["season"] == val_season) & (df_with_tour["tour"] >= i))]["match_result"]

    X_val = df_with_tour[(df_with_tour["season"] == val_season) & (df_with_tour["tour"] == i)].drop(columns=unknown_cols)
    y_val = df_with_tour[(df_with_tour["season"] == val_season) & (df_with_tour["tour"] == i)]["match_result"]
    
    X_test = df_with_tour[(df_with_tour["season"] == val_season) & (df_with_tour["tour"] == i + 1)].drop(columns=unknown_cols)
    y_test = df_with_tour[(df_with_tour["season"] == val_season) & (df_with_tour["tour"] == i + 1)]["match_result"]

    train_pool = Pool(
        data=X_train,
        label=y_train,
        cat_features=cat_columns
    )
    
    val_pool = Pool(
        data=X_val,
        label=y_val,
        cat_features=cat_columns
    )

    test_pool = Pool(
        data=X_test,
        label=y_test,
        cat_features=cat_columns
    )

    model = CatBoostClassifier(
        iterations=3000,
        learning_rate=0.005,
        depth=6,
        loss_function='MultiClass',
        random_seed=42,
        verbose=100,
        cat_features=cat_columns,
    )
    model.fit(
        X_train, y_train,
        eval_set=(X_val, y_val),
        early_stopping_rounds=50,
        verbose=100
    )

    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)
    
    acc_score = accuracy_score(y_test, y_pred)
    acc_scores.append(acc_score)
    
    print("="*50)
    print(i, acc_score)
    print("="*50)
          
print(np.mean(acc_scores))

0:	learn: 1.0977996	test: 1.0980662	best: 1.0980662 (0)	total: 125ms	remaining: 6m 15s
100:	learn: 1.0437971	test: 1.0870138	best: 1.0869636 (94)	total: 11s	remaining: 5m 16s
200:	learn: 1.0203143	test: 1.0849609	best: 1.0839087 (172)	total: 22s	remaining: 5m 6s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.083908665
bestIteration = 172

Shrink model to first 173 iterations.
==================================================
31 0.6
==================================================
0:	learn: 1.0977890	test: 1.0973837	best: 1.0973837 (0)	total: 121ms	remaining: 6m 1s
100:	learn: 1.0438586	test: 1.0125961	best: 1.0125961 (100)	total: 11.2s	remaining: 5m 20s
200:	learn: 1.0206911	test: 0.9697565	best: 0.9697565 (200)	total: 22.2s	remaining: 5m 9s
300:	learn: 1.0087300	test: 0.9464303	best: 0.9464303 (300)	total: 33.3s	remaining: 4m 58s
400:	learn: 1.0016205	test: 0.9344185	best: 0.9344185 (400)	total: 44.2s	remaining: 4m 46s
500:	learn: 0.9968788	test: 0.9284698	best: 0.9283386 (499)	total: 54.9s	remaining: 4m 33s
600:	learn: 0.9931625	test: 0.9255575	best: 0.9255575 (600)	total: 1m 5s	remaining: 4m 20s
700:	learn: 0.9899347	test: 0.9241700	best: 0.9239770 (697)	total: 1m 15s	remaining: 4m 8s
800:	learn: 0.9869601	test: 0.9227654	best: 0.9226900 (782)	total: 1m 26s	remaining: 3m 56s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.922609034
bestIteration = 804

Shrink model to first 805 iterations.
==================================================
32 0.45
==================================================
0:	learn: 1.0977611	test: 1.0989906	best: 1.0989906 (0)	total: 129ms	remaining: 6m 25s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.098990642
bestIteration = 0

Shrink model to first 1 iterations.
==================================================
33 0.4
==================================================
0:	learn: 1.0977409	test: 1.0985907	best: 1.0985907 (0)	total: 119ms	remaining: 5m 56s
100:	learn: 1.0441162	test: 1.0899740	best: 1.0892368 (83)	total: 11s	remaining: 5m 15s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.089028401
bestIteration = 119

Shrink model to first 120 iterations.
==================================================
34 0.375
==================================================
0:	learn: 1.0978563	test: 1.0979854	best: 1.0979854 (0)	total: 105ms	remaining: 5m 14s
100:	learn: 1.0437264	test: 1.0694244	best: 1.0694244 (100)	total: 10.9s	remaining: 5m 13s
200:	learn: 1.0207042	test: 1.0560576	best: 1.0560576 (200)	total: 21.9s	remaining: 5m 4s
300:	learn: 1.0090143	test: 1.0482057	best: 1.0478060 (290)	total: 32.9s	remaining: 4m 55s
400:	learn: 1.0019444	test: 1.0419597	best: 1.0417024 (390)	total: 43.9s	remaining: 4m 44s
500:	learn: 0.9971270	test: 1.0398274	best: 1.0396750 (497)	total: 54.5s	remaining: 4m 31s
600:	learn: 0.9932553	test: 1.0386542	best: 1.0382825 (567)	total: 1m 4s	remaining: 4m 19s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.038282472
bestIteration = 567

Shrink model to first 568 iterations.
==================================================
35 0.5625
==================================================
0:	learn: 1.0977561	test: 1.0967219	best: 1.0967219 (0)	total: 114ms	remaining: 5m 41s
100:	learn: 1.0439816	test: 0.9734900	best: 0.9734900 (100)	total: 11.1s	remaining: 5m 18s
200:	learn: 1.0206933	test: 0.9189338	best: 0.9189338 (200)	total: 22.2s	remaining: 5m 9s
300:	learn: 1.0089268	test: 0.8916205	best: 0.8916205 (300)	total: 33.4s	remaining: 4m 59s
400:	learn: 1.0019567	test: 0.8772178	best: 0.8772178 (400)	total: 44.3s	remaining: 4m 47s
500:	learn: 0.9971094	test: 0.8697613	best: 0.8697613 (500)	total: 55s	remaining: 4m 34s
600:	learn: 0.9933347	test: 0.8647094	best: 0.8646681 (599)	total: 1m 5s	remaining: 4m 22s
700:	learn: 0.9901469	test: 0.8613859	best: 0.8613859 (700)	total: 1m 16s	remaining: 4m 9s
800:	learn: 0.9872533	test: 0.8585477	best: 0.8584610 (798)	total: 1m 26s	remaining: 3m 57s
900:	learn: 0.9847075	test: 0.8570006	best: 0.8569991 (899)	total: 1m 37s	remaining: 3m 46s
1000:	learn: 0.9822355	test: 0.8566368	best: 0.8562054 (977)	total: 1m 47s	remaining: 3m 34s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.8562053534
bestIteration = 977

Shrink model to first 978 iterations.
==================================================
36 0.7222222222222222
==================================================
0:	learn: 1.0977593	test: 1.0981477	best: 1.0981477 (0)	total: 138ms	remaining: 6m 53s
100:	learn: 1.0436202	test: 1.0625465	best: 1.0625465 (100)	total: 11s	remaining: 5m 15s
200:	learn: 1.0204133	test: 1.0422793	best: 1.0422793 (200)	total: 21.9s	remaining: 5m 5s
300:	learn: 1.0086858	test: 1.0272724	best: 1.0272724 (300)	total: 32.9s	remaining: 4m 54s
400:	learn: 1.0017035	test: 1.0170925	best: 1.0170925 (400)	total: 43.7s	remaining: 4m 43s
500:	learn: 0.9969723	test: 1.0100617	best: 1.0100617 (500)	total: 54.4s	remaining: 4m 31s
600:	learn: 0.9932376	test: 1.0030990	best: 1.0030990 (600)	total: 1m 5s	remaining: 4m 19s
700:	learn: 0.9900634	test: 0.9986530	best: 0.9985639 (699)	total: 1m 15s	remaining: 4m 7s
800:	learn: 0.9873521	test: 0.9947123	best: 0.9946991 (799)	total: 1m 25s	remaining: 3m 55s
900:	learn: 0.9847653	test: 0.9916591	best: 0.9916591 (900)	total: 1m 36s	remaining: 3m 44s
1000:	learn: 0.9822108	test: 0.9903227	best: 0.9902131 (994)	total: 1m 46s	remaining: 3m 33s
1100:	learn: 0.9799227	test: 0.9881250	best: 0.9881175 (1070)	total: 1m 57s	remaining: 3m 22s
1200:	learn: 0.9776518	test: 0.9853085	best: 0.9852938 (1199)	total: 2m 7s	remaining: 3m 10s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.9845830489
bestIteration = 1219

Shrink model to first 1220 iterations.
==================================================
37 0.25
==================================================
0:	learn: 1.0977810	test: 1.0988817	best: 1.0988817 (0)	total: 118ms	remaining: 5m 54s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.098881685
bestIteration = 0

Shrink model to first 1 iterations.
==================================================
38 0.35
==================================================
0:	learn: 1.0977516	test: 1.0991406	best: 1.0991406 (0)	total: 123ms	remaining: 6m 10s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.099140606
bestIteration = 0

Shrink model to first 1 iterations.
==================================================
39 0.55
==================================================
0:	learn: 1.0977501	test: 1.0978611	best: 1.0978611 (0)	total: 131ms	remaining: 6m 32s
100:	learn: 1.0440622	test: 1.0400044	best: 1.0400044 (100)	total: 11.1s	remaining: 5m 18s
200:	learn: 1.0209813	test: 1.0117152	best: 1.0117152 (200)	total: 22.1s	remaining: 5m 7s
300:	learn: 1.0091525	test: 0.9938074	best: 0.9938074 (300)	total: 33.1s	remaining: 4m 57s
400:	learn: 1.0022311	test: 0.9828458	best: 0.9828317 (398)	total: 44.1s	remaining: 4m 45s
500:	learn: 0.9975038	test: 0.9756643	best: 0.9756643 (500)	total: 54.8s	remaining: 4m 33s
600:	learn: 0.9938746	test: 0.9716561	best: 0.9716561 (600)	total: 1m 5s	remaining: 4m 21s
700:	learn: 0.9906652	test: 0.9685183	best: 0.9685183 (700)	total: 1m 15s	remaining: 4m 8s
800:	learn: 0.9878329	test: 0.9661572	best: 0.9659504 (761)	total: 1m 26s	remaining: 3m 57s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.9659504245
bestIteration = 761

Shrink model to first 762 iterations.
==================================================
40 0.6
==================================================
0.48597222222222225

то же самое но обучаемся на последний сезон

In [70]:
acc_scores = []
for i in range(n - 10 - 1, n-1):
    X_train = df_with_tour[(df_with_tour["season"] == val_season) & (df_with_tour["tour"] < i)].drop(columns=unknown_cols)
    y_train = df_with_tour[(df_with_tour["season"] == val_season) & (df_with_tour["tour"] < i)]["match_result"]

    X_val = df_with_tour[(df_with_tour["season"] == val_season) & (df_with_tour["tour"] == i)].drop(columns=unknown_cols)
    y_val = df_with_tour[(df_with_tour["season"] == val_season) & (df_with_tour["tour"] == i)]["match_result"]
    
    X_test = df_with_tour[(df_with_tour["season"] == val_season) & (df_with_tour["tour"] == i + 1)].drop(columns=unknown_cols)
    y_test = df_with_tour[(df_with_tour["season"] == val_season) & (df_with_tour["tour"] == i + 1)]["match_result"]

    train_pool = Pool(
        data=X_train,
        label=y_train,
        cat_features=cat_columns
    )
    
    val_pool = Pool(
        data=X_val,
        label=y_val,
        cat_features=cat_columns
    )

    test_pool = Pool(
        data=X_test,
        label=y_test,
        cat_features=cat_columns
    )

    model = CatBoostClassifier(
        iterations=3000,
        learning_rate=0.005,
        depth=6,
        loss_function='MultiClass',
        random_seed=42,
        verbose=100,
        cat_features=cat_columns,
    )
    model.fit(
        X_train, y_train,
        eval_set=(X_val, y_val),
        early_stopping_rounds=50,
        verbose=100
    )

    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)
    
    acc_score = accuracy_score(y_test, y_pred)
    acc_scores.append(acc_score)
    
    print("="*50)
    print(i, acc_score)
    print("="*50)
          
print(np.mean(acc_scores))

0:	learn: 1.0979129	test: 1.0978705	best: 1.0978705 (0)	total: 47.7ms	remaining: 2m 23s
100:	learn: 1.0293662	test: 1.0576783	best: 1.0576783 (100)	total: 4.31s	remaining: 2m 3s
200:	learn: 0.9761475	test: 1.0337912	best: 1.0337912 (200)	total: 8.55s	remaining: 1m 59s
300:	learn: 0.9315161	test: 1.0143083	best: 1.0143083 (300)	total: 12.9s	remaining: 1m 55s
400:	learn: 0.8927027	test: 1.0045730	best: 1.0045730 (400)	total: 17s	remaining: 1m 50s
500:	learn: 0.8586713	test: 0.9999159	best: 0.9999159 (500)	total: 21.1s	remaining: 1m 45s
600:	learn: 0.8271825	test: 0.9924402	best: 0.9924402 (600)	total: 25.5s	remaining: 1m 41s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.9899244988
bestIteration = 641

Shrink model to first 642 iterations.
==================================================
31 0.6
==================================================
0:	learn: 1.0979687	test: 1.0981356	best: 1.0981356 (0)	total: 49.8ms	remaining: 2m 29s
100:	learn: 1.0306649	test: 1.0685476	best: 1.0685476 (100)	total: 4.15s	remaining: 1m 59s
200:	learn: 0.9790650	test: 1.0506415	best: 1.0506415 (200)	total: 8.33s	remaining: 1m 56s
300:	learn: 0.9346115	test: 1.0354589	best: 1.0354589 (300)	total: 12.5s	remaining: 1m 52s
400:	learn: 0.8962858	test: 1.0265971	best: 1.0265971 (400)	total: 16.7s	remaining: 1m 48s
500:	learn: 0.8634384	test: 1.0229939	best: 1.0228903 (497)	total: 21.1s	remaining: 1m 45s
600:	learn: 0.8341075	test: 1.0205248	best: 1.0204575 (571)	total: 25.2s	remaining: 1m 40s
700:	learn: 0.8050013	test: 1.0173476	best: 1.0169257 (696)	total: 29.7s	remaining: 1m 37s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.016764507
bestIteration = 720

Shrink model to first 721 iterations.
==================================================
32 0.45
==================================================
0:	learn: 1.0977126	test: 1.0983491	best: 1.0983491 (0)	total: 34.4ms	remaining: 1m 43s
100:	learn: 1.0303950	test: 1.0835586	best: 1.0834281 (92)	total: 4.14s	remaining: 1m 58s
200:	learn: 0.9773736	test: 1.0703456	best: 1.0703456 (200)	total: 8.27s	remaining: 1m 55s
300:	learn: 0.9337570	test: 1.0681383	best: 1.0679794 (288)	total: 12.6s	remaining: 1m 53s
400:	learn: 0.8976416	test: 1.0671074	best: 1.0659229 (388)	total: 16.7s	remaining: 1m 48s
500:	learn: 0.8647786	test: 1.0612505	best: 1.0612505 (500)	total: 20.8s	remaining: 1m 43s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.061244646
bestIteration = 503

Shrink model to first 504 iterations.
==================================================
33 0.45
==================================================
0:	learn: 1.0977998	test: 1.0981956	best: 1.0981956 (0)	total: 34.6ms	remaining: 1m 43s
100:	learn: 1.0319301	test: 1.0730813	best: 1.0729698 (99)	total: 4.3s	remaining: 2m 3s
200:	learn: 0.9812337	test: 1.0629835	best: 1.0629835 (200)	total: 8.37s	remaining: 1m 56s
300:	learn: 0.9397938	test: 1.0565730	best: 1.0565730 (300)	total: 12.6s	remaining: 1m 53s
400:	learn: 0.9021302	test: 1.0487705	best: 1.0486060 (388)	total: 16.9s	remaining: 1m 49s
500:	learn: 0.8682478	test: 1.0477005	best: 1.0465642 (468)	total: 21.2s	remaining: 1m 45s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.046298467
bestIteration = 528

Shrink model to first 529 iterations.
==================================================
34 0.5
==================================================
0:	learn: 1.0979395	test: 1.0986686	best: 1.0986686 (0)	total: 35.5ms	remaining: 1m 46s
100:	learn: 1.0337072	test: 1.0861251	best: 1.0861251 (100)	total: 4.21s	remaining: 2m
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.081638599
bestIteration = 131

Shrink model to first 132 iterations.
==================================================
35 0.5625
==================================================
0:	learn: 1.0978506	test: 1.0970621	best: 1.0970621 (0)	total: 48.6ms	remaining: 2m 25s
100:	learn: 1.0332530	test: 1.0416173	best: 1.0416173 (100)	total: 4.31s	remaining: 2m 3s
200:	learn: 0.9822279	test: 0.9998634	best: 0.9998634 (200)	total: 8.38s	remaining: 1m 56s
300:	learn: 0.9409249	test: 0.9687328	best: 0.9687328 (300)	total: 12.6s	remaining: 1m 53s
400:	learn: 0.9056349	test: 0.9471344	best: 0.9471344 (400)	total: 16.9s	remaining: 1m 49s
500:	learn: 0.8737908	test: 0.9323304	best: 0.9323304 (500)	total: 21.1s	remaining: 1m 45s
600:	learn: 0.8439577	test: 0.9245386	best: 0.9245386 (600)	total: 25.4s	remaining: 1m 41s
700:	learn: 0.8166248	test: 0.9142150	best: 0.9142150 (700)	total: 29.5s	remaining: 1m 36s
800:	learn: 0.7903854	test: 0.9115044	best: 0.9115044 (800)	total: 33.7s	remaining: 1m 32s
900:	learn: 0.7658859	test: 0.9078170	best: 0.9069468 (889)	total: 37.9s	remaining: 1m 28s
1000:	learn: 0.7422912	test: 0.9026235	best: 0.9021085 (993)	total: 42.1s	remaining: 1m 24s
1100:	learn: 0.7199969	test: 0.8997907	best: 0.8981223 (1079)	total: 46.3s	remaining: 1m 19s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.8981222846
bestIteration = 1079

Shrink model to first 1080 iterations.
==================================================
36 0.6666666666666666
==================================================
0:	learn: 1.0979834	test: 1.0976895	best: 1.0976895 (0)	total: 49ms	remaining: 2m 26s
100:	learn: 1.0327211	test: 1.0122758	best: 1.0122758 (100)	total: 4.12s	remaining: 1m 58s
200:	learn: 0.9828255	test: 0.9630174	best: 0.9630174 (200)	total: 8.34s	remaining: 1m 56s
300:	learn: 0.9432306	test: 0.9280081	best: 0.9280081 (300)	total: 12.6s	remaining: 1m 53s
400:	learn: 0.9068349	test: 0.9019607	best: 0.9019607 (400)	total: 16.6s	remaining: 1m 47s
500:	learn: 0.8760319	test: 0.8830525	best: 0.8830525 (500)	total: 20.8s	remaining: 1m 43s
600:	learn: 0.8460443	test: 0.8674846	best: 0.8674846 (600)	total: 24.8s	remaining: 1m 38s
700:	learn: 0.8191291	test: 0.8532172	best: 0.8532172 (700)	total: 28.9s	remaining: 1m 34s
800:	learn: 0.7925298	test: 0.8376897	best: 0.8376897 (800)	total: 33.2s	remaining: 1m 31s
900:	learn: 0.7683594	test: 0.8298809	best: 0.8297444 (899)	total: 37.3s	remaining: 1m 26s
1000:	learn: 0.7458449	test: 0.8191485	best: 0.8191485 (1000)	total: 41.4s	remaining: 1m 22s
1100:	learn: 0.7226085	test: 0.8134612	best: 0.8134612 (1100)	total: 45.5s	remaining: 1m 18s
1200:	learn: 0.7013360	test: 0.8056131	best: 0.8056131 (1200)	total: 49.5s	remaining: 1m 14s
1300:	learn: 0.6780862	test: 0.8002994	best: 0.8002994 (1300)	total: 53.8s	remaining: 1m 10s
1400:	learn: 0.6553006	test: 0.7935375	best: 0.7933956 (1394)	total: 58s	remaining: 1m 6s
1500:	learn: 0.6334264	test: 0.7880464	best: 0.7880417 (1499)	total: 1m 2s	remaining: 1m 2s
1600:	learn: 0.6110280	test: 0.7812075	best: 0.7811574 (1599)	total: 1m 6s	remaining: 58s
1700:	learn: 0.5901602	test: 0.7771719	best: 0.7771197 (1698)	total: 1m 10s	remaining: 54s
1800:	learn: 0.5684656	test: 0.7751334	best: 0.7748530 (1769)	total: 1m 14s	remaining: 49.9s
1900:	learn: 0.5481720	test: 0.7724903	best: 0.7718196 (1875)	total: 1m 19s	remaining: 45.8s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.7718195531
bestIteration = 1875

Shrink model to first 1876 iterations.
==================================================
37 0.2
==================================================
0:	learn: 1.0979594	test: 1.0985974	best: 1.0985974 (0)	total: 35.1ms	remaining: 1m 45s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.098597372
bestIteration = 0

Shrink model to first 1 iterations.
==================================================
38 0.5
==================================================
0:	learn: 1.0979125	test: 1.0985695	best: 1.0985695 (0)	total: 48.9ms	remaining: 2m 26s
100:	learn: 1.0312230	test: 1.0984838	best: 1.0937723 (55)	total: 4.15s	remaining: 1m 59s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 1.093772271
bestIteration = 55

Shrink model to first 56 iterations.
==================================================
39 0.7
==================================================
0:	learn: 1.0980521	test: 1.0980020	best: 1.0980020 (0)	total: 45.1ms	remaining: 2m 15s
100:	learn: 1.0357422	test: 1.0366468	best: 1.0366468 (100)	total: 4.3s	remaining: 2m 3s
200:	learn: 0.9871463	test: 0.9907385	best: 0.9907385 (200)	total: 8.62s	remaining: 1m 59s
300:	learn: 0.9470620	test: 0.9563537	best: 0.9563537 (300)	total: 13s	remaining: 1m 56s
400:	learn: 0.9119784	test: 0.9385040	best: 0.9384498 (398)	total: 17.1s	remaining: 1m 50s
500:	learn: 0.8808499	test: 0.9240351	best: 0.9235886 (496)	total: 21.3s	remaining: 1m 46s
600:	learn: 0.8520584	test: 0.9109507	best: 0.9109507 (600)	total: 25.5s	remaining: 1m 41s
700:	learn: 0.8259929	test: 0.9006032	best: 0.9004356 (696)	total: 29.6s	remaining: 1m 36s
800:	learn: 0.8023349	test: 0.8939176	best: 0.8935643 (797)	total: 33.8s	remaining: 1m 32s
900:	learn: 0.7783044	test: 0.8889910	best: 0.8888869 (891)	total: 38.1s	remaining: 1m 28s
1000:	learn: 0.7562488	test: 0.8861159	best: 0.8844214 (986)	total: 42.2s	remaining: 1m 24s
1100:	learn: 0.7348836	test: 0.8827727	best: 0.8825105 (1098)	total: 46.4s	remaining: 1m 20s
1200:	learn: 0.7137332	test: 0.8793093	best: 0.8792520 (1199)	total: 50.6s	remaining: 1m 15s
1300:	learn: 0.6929485	test: 0.8771280	best: 0.8769257 (1298)	total: 55s	remaining: 1m 11s
1400:	learn: 0.6723203	test: 0.8751689	best: 0.8751579 (1391)	total: 59.5s	remaining: 1m 7s
1500:	learn: 0.6506529	test: 0.8690639	best: 0.8690639 (1500)	total: 1m 3s	remaining: 1m 3s
1600:	learn: 0.6296022	test: 0.8665902	best: 0.8665902 (1600)	total: 1m 8s	remaining: 59.6s
1700:	learn: 0.6087644	test: 0.8628718	best: 0.8628718 (1700)	total: 1m 12s	remaining: 55.4s
1800:	learn: 0.5888449	test: 0.8595266	best: 0.8595266 (1800)	total: 1m 16s	remaining: 51.2s
1900:	learn: 0.5686807	test: 0.8565691	best: 0.8565691 (1900)	total: 1m 21s	remaining: 46.9s
2000:	learn: 0.5491906	test: 0.8520149	best: 0.8515714 (1991)	total: 1m 25s	remaining: 42.6s
2100:	learn: 0.5304475	test: 0.8503308	best: 0.8502233 (2064)	total: 1m 29s	remaining: 38.3s
2200:	learn: 0.5134881	test: 0.8493307	best: 0.8487759 (2193)	total: 1m 33s	remaining: 34s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.8487758522
bestIteration = 2193

Shrink model to first 2194 iterations.
==================================================
40 0.6
==================================================
0.5229166666666666